name: code_gen_tester
version: 0.0.1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  source_gen: ^0.9.5
  build: ^1.2.2
  analyzer: ^0.39.4
  test: ^1.11.1
  dart_style: ^1.3.3
  pedantic: ^1.4.0
  build_runner: ^1.8.0
  build_test: ^0.10.6
