name: functional_widget
description: A code generator that generates widget classes from their implementation as a function.
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/functional_widget/tree/master/functional_widget
version: 0.7.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # flutter:
  #   sdk: flutter
  functional_widget_annotation: ^0.5.0
  source_gen: ^0.9.5
  build_config: ^0.4.0
  build: ^1.2.2
  analyzer: ^0.39.4
  meta: ^1.1.7

dev_dependencies:
  # flutter_hooks: any
  # flutter_test:
  #   sdk: flutter
  test:
  mockito: ^4.1.0
  dart_style: ^1.3.3
  pedantic: ^1.4.0
  build_runner: ^1.8.0
  build_test: ^0.10.11
